#@package _global_
defaults:
  - /mephisto/blueprint: model_chat_blueprint
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    annotations_config_path: ${task_dir}/task_config/annotations_config.json #'' #
    onboarding_qualification: model_chat_onboarding 
    block_qualification: model_chat_block
    max_onboard_time: 10000
    chat_data_folder: ${task_dir}/model_chat/
    model_opt_path: ${task_dir}/task_config/model_opts.yaml
    num_turns: 6
    task_model_parallel: false
    check_acceptability: false
    include_persona: false
    conversation_start_mode: 'hi_diff_lang'
    start_language: 'fi'
    lang_in_use: 'Finnish'
    final_rating_question: >-
      Please rate how much you'd prefer to talk to your partner for a long conversation.
      (1: Would not at all prefer, 5: Would very much prefer)|Please rate how interesting your
      partner is. (1: Very boring, 5: Very interesting)|Please rate how factually accurate your
      partner's responses are. (1: Very inaccurate, 5: Very accurate)|Please rate how fluent and grammatical your
      partner's responses are. (1: Very unfluent and gramatically incorrect, 5: Very fluent and gramatically correct)|
      Please rate how sensible and relevant your partner is. (1: Very irrelevant and non-sensible, 5: Very relevant and sensible)|
      Please rate how knowledgeable and/or informative your partner is (1: Very unknowledgeable, 5: Very knowledgeable)
    conversations_needed_string: "blender_400M:1,genmdm_400M:1,mgen:2"
    onboard_task_data_path: ${task_dir}/task_config/onboard_task_data.json
    task_description_file: ${task_dir}/task_config/task_description.html
    left_pane_text_path: ${task_dir}/task_config/left_pane_text.html
  task:
    allowed_concurrent: 5
    assignment_duration_in_seconds: 10000
    max_num_concurrent_units: 5  # 0 means infinite; set this to a positive integer to limit concurrent HITs and prevent crashes
    maximum_units_per_worker: 10000
    task_description: dummy_text  # This is unused
    task_name: single_model_fi
    task_reward: 0
    task_tags: "chat,conversation,dialog,partner"
    task_title: "Chat with a fellow conversationalist!"
mturk:
  worker_blocklist_paths: null
    #annotation_question: Does this comment from your partner have any of the following attributes? (Check all that apply)