#@package _global_
defaults:
  - /mephisto/blueprint: my_per_turn_eval_blueprint
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    annotations_config_path: ${task_dir}/task_config/annotations_config.json
    onboarding_qualification: per_turn_eval_onboarding__engaging
    block_on_onboarding_fail: false
    max_onboard_time: 10000
    world_file: /home/evelyn/parley/parlai/crowdsourcing/tasks/my_pw_per_turn/worlds.py
    block_qualification: per_turn_eval_${current_time}_block
    chat_data_folder: /home/evelyn/parley/parlai/crowdsourcing/tasks/my_pw_per_turn/model_chat/ 
    model_opt_path: ${task_dir}/task_config/model_opts.yaml
    custom_source_dir: /home/evelyn/parley/parlai/crowdsourcing/tasks/my_pw_per_turn/frontend
    num_turns: 6
    task_model_parallel: true
    check_acceptability: false
    include_persona: false
    conversation_start_mode: 'hi_diff_lang'
    start_language: 'ko'
    lang_in_use: 'Korean' #Bengali
    annotation_question: Which of these following two responses from your partner would you prefer in a long conversation? (Select one)
    task_question: "Which next response from your partner would you prefer in a long conversation?"
    conversations_needed_string: "mgen:blender_400M:genmdm_400M:10"
    max_resp_time: 3600
    onboard_task_data_path: ${task_dir}/task_config/onboard_task_data__engaging.json
  task:
    allowed_concurrent: 1
    assignment_duration_in_seconds: 36000  # Set to an hour because models are sometimes slow and Turkers get distracted
    max_num_concurrent_units: 5  # 0 means infinite; set this to a positive integer to limit concurrent HITs and prevent crashes
    maximum_units_per_worker: 100000
    task_description: dummy_text  # TODO: this shouldn't have to be specified, since this text will be never shown. We're specifying the task description in the task_config/ folder instead.
    task_name: per_turn_eval_ko # We are evaluating engagingness in this run - modify for your use
    task_reward: 0
    task_tags: "chat,conversation,dialog,partner"
    task_title: "Chat with a fellow conversationalist!"
    
    #annotation_question: Does this comment from your partner have any of the following attributes? (Check all that apply)